"""add password hash

Revision ID: fbb11e0b3f86
Revises: 2a2b1f068edb
Create Date: 2026-02-19 14:56:15.407041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb11e0b3f86'
down_revision: Union[str, Sequence[str], None] = '2a2b1f068edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    # 1. add column nullable first
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))

    # 2. give default password to old users (temporary)
    op.execute("UPDATE users SET password_hash = 'temp_password'")

    # 3. now make it NOT NULL
    op.alter_column('users', 'password_hash', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
